import { ApiProperty } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import {
  IsArray,
  IsBoolean,
  IsNotEmpty,
  IsNumber,
  IsOptional,
  IsString,
  ValidateNested,
} from 'class-validator';

export class TimeSlot {
  @ApiProperty({ description: 'Start time (12-hour format)', example: '08:00 AM' })
  @IsNotEmpty()
  @IsString()
  startTime!: string;

  @ApiProperty({ description: 'End time (12-hour format)', example: '06:00 PM' })
  @IsNotEmpty()
  @IsString()
  endTime!: string;
}

export class ItineraryActivity {
  @ApiProperty({ description: 'Activity title', example: 'Arrival and check-in' })
  @IsNotEmpty()
  @IsString()
  title!: string;

  @ApiProperty({
    description: 'Activity time slot',
    type: TimeSlot,
  })
  @ValidateNested()
  @Type(() => TimeSlot)
  timeSlot!: TimeSlot;

  @ApiProperty({
    description: 'Activity notes',
    type: [String],
    example: [
      'Travel from Moratuwa to Kandy',
      'Take a short refreshment break',
    ],
    required: false,
  })
  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  notes?: string[];

  @ApiProperty({
    description: 'Whether this activity was generated by AI',
    example: false,
    required: false,
  })
  @IsOptional()
  @IsBoolean()
  isAIGenerated?: boolean;
}

export class ItineraryDay {
  @ApiProperty({ description: 'Day number', example: 1 })
  @IsNotEmpty()
  @IsNumber()
  day!: number;

  @ApiProperty({ description: 'Day title', example: 'Day 1' })
  @IsNotEmpty()
  @IsString()
  title!: string;

  @ApiProperty({
    description: 'Activities for the day',
    type: [ItineraryActivity],
  })
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => ItineraryActivity)
  activities!: ItineraryActivity[];
}

export class Itinerary {
  @ApiProperty({
    description: 'Daily itinerary',
    type: [ItineraryDay],
  })
  @IsNotEmpty()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => ItineraryDay)
  days!: ItineraryDay[];
}